builds:
  - id: sd
    main: ./cmd/sd
    binary: sd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "sd_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
