builds:
  - id: scd
    main: ./cmd/scd
    binary: scd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "scd_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
